# Generated by Django 5.2.7 on 2025-11-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_servicedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='services_icons/'),
        ),
    ]
