# Generated by Django 5.2.7 on 2025-11-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_service_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icone',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
