# Generated by Django 5.2.7 on 2025-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_service_description_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icone',
        ),
    ]
