# Generated by Django 5.2.7 on 2025-11-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_service_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='services/default.jpg', null=True, upload_to='services/'),
        ),
    ]
