# Generated by Django 5.2.7 on 2025-11-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_service_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
    ]
