# Generated by Django 5.2.7 on 2025-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True)),
                ('texte', models.TextField()),
                ('note', models.PositiveIntegerField(default=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
