# Generated by Django 5.2.7 on 2025-11-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_temoignage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de galerie',
                'verbose_name_plural': 'Catégories de galerie',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PhotoGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='galerie/', verbose_name='Image')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.categoriegalerie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Photo de galerie',
                'verbose_name_plural': 'Photos de galerie',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
