# Generated by Django 5.2.7 on 2025-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='etat',
            field=models.CharField(choices=[('avant', 'Avant les travaux'), ('apres', 'Après les travaux')], default='avant', max_length=10),
        ),
    ]
