# Generated by Django 5.2.13 on 2026-04-23 23:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_projectimage_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('resume', models.CharField(help_text='Courte description (affiché dans la liste)', max_length=300)),
                ('contenu', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('categorie', models.CharField(choices=[('conseil', 'Conseils & Astuces'), ('realisation', 'Réalisation'), ('actualite', 'Actualité')], default='conseil', max_length=20)),
                ('meta_description', models.CharField(blank=True, help_text='Description SEO (max 160 caractères)', max_length=160)),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
    ]
