# Generated by Django 5.0.1 on 2026-05-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_article_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.CharField(default='Performance Habitat', help_text="Nom de l'auteur", max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='date_modification',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='mots_cles',
            field=models.CharField(blank=True, help_text='Mots-clés SEO séparés par des virgules', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description SEO (max 160 caractères)', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='type_travaux',
            field=models.CharField(blank=True, help_text='Ex: Salle de bain, Plomberie', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='ville',
            field=models.CharField(blank=True, help_text='Ex: Brest, Guilers, Plouzané', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du service (visible sur la page)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description SEO (max 160 caractères)', max_length=160),
        ),
    ]
